### ISSUE TITLE
suggestion: split into multiple message types

### ISSUE THREAD

**Issue by dominictarr** [ssbc/ssb-same-as#3]
Instead of loading same-as into contact message type, I suggest we use a different message type.
To get backwards compat, just also create a normal contact/follow message (if you are not already following)

combining all these into one type of message (contact messages are for following, blocking 
- combining two feeds you control, and claiming that two other feeds are the same) that makes any thing that processes contact messages have to be more complicated. I think it would easier to build ssb applications (or, to upgrade applications) if there were more tightly focused message types.

**Comment by dominictarr** [comment]
@mmckegg what are you thoughts on this? I'd like to use same-as as part of user invites, and as part of pubs as devices `%Gwqklkj0b2CBT5tPiz5170NWsPp3xiuLbOImEaG/e+4=.sha256`
I would much prefer a separate message type, and I also need a signal that the pub shouldn't be a recipient of private messages addressed to the owner (unlike their phone)

I'm thinking something like:

```
msg_propose_id = {
  type: 'same-as',
  sameAs: @pub_id,
  private: false, //don't include in private messages
  secondary: true //the author of this message is the main device, not the linked to device.
}
```

then, I think an accept should point back to the suggest.

```
msg_accept_id = {
  type: "same-as/accept",
  accept: msg_propose_id
}
```
then, confirm
```
{
  type: "same-as/confirm",
  confirm: msg_accept_id
}
```
accept and confirm can be retrived out-of-order so we won't need to automatically follow anyone they say is also them. Also, this makes it clear which is the main device.

The aspect of patchwork's same-as that user-invites needs, is that if you replicate one peer, you should also replicate peers which are same-as them. But the difference is that you don't want to send private messages to their pub. (second thought: represent this across two separate message types?)

**Comment by mmckegg** [comment]
@dominictarr

I think I like this a lot! I wasn’t thinking in terms of ooo when I specced this. 

👍

**Comment by dominictarr** [comment]
@mmckegg okay, great.

additional context: I'm looking for repeatable patterns, and this is very similar to what I've come up with for [user-invites](https://github.com/dominictarr/user-invites). The `same-as` is essentially an agreement between two uxers that causes computers to automatically respond... so it's what you could call a "smart contract".

I have a hunch that having the accept and confirm messages be really locked in (so you know exactly what proposal is agreed to, via hash, will end up being important.

oh I should probably specify a way to cancel a same-as, too, in case you loose a device.

**Comment by dominictarr** [comment]
@bhaugen I realized that my proposal here is quite similar to the vocabulary you are using for valueflows... it's really just about making an agreement between two identities. I don't really mind what the operations are called, so maybe this is a good time to set common patterns.

**Comment by bhaugen** [comment]
@fosterlynn is the lead on valueflows so I am pinging her here, too.

@dominictarr which part of the VF vocab did you have in mind? This might be more in the common protocols territory. The only one of those that we have specified informally is [Conversation for Action](https://www.valueflo.ws/introduction/cfa.html) which is probably overkill for same-as and not the same as user-invites. But interaction protocols are always interesting and we want to include more of them, so thanks for asking.

I'll think about this and talk to Lynn later and see what we might be able to add to the discussion here, and then maybe harvest for VF.

**Comment by dominictarr** [comment]
@bhaugen I'm not sure, but it seemed like something you might be interested in.
It definitely seemed simpler than some of the VF patterns,
but I guess we have a `propose/accept/confirm` pattern, and invites are `propose/accept/witness`

(it's called `confirm` in user invites recently, but maybe since it's a 3rd party that does the confirm it's more like witnessing someone else's signature)

**Comment by bhaugen** [comment]
We are definitely interested, and are discussing, and will respond I hope usefully tomorrow.

**Comment by bhaugen** [comment]
@dominictarr how deep do you want to go in a conversation about this topic? I'll ramble a bit and see if we connect. 

Short version: I like the pattern you described in [this comment above-thread](https://github.com/ssbc/ssb-same-as/issues/3#issuecomment-381497200) and think it will work. We have not yet formalized such a pattern in VF, so I'll post this over there as an issue and see what people think.

The general topic has been called message sequence patterns or interaction protocols. We've discussed those some in VF but so far I seem to be the only person who is focused on them, so it's good to have some conversation partners. And we can set some common patterns here.

The specific topic is, as you wrote
> making an agreement between two identities.

What I see as vocabulary here, besides "same-as" and "cancel", are some specific vocab about managing the agreement: "propose", "accept", "confirm", and an implicit sequence re citing the id of the previous message, e.g. 
>   confirm: msg_accept_id

Conversation for Action (CfA) uses "request" as the sequence-initiator, but I like "propose" in this case. I'm not sure what situations would want which of those words. 

Is this an agreement between two nodes conducted by an async message exchange on an unreliable network? In that case, I think "``` I have a hunch that having the accept and confirm messages be really locked in (so you know exactly what proposal is agreed to, via hash, will end up being important```" will be more than a hunch. Would be interesting to detail what could go wrong, and why you need that final "confirm", that is, why propose-accept is not enough.

See also [this windy previous conversation between me and Lynn](https://docs.google.com/document/d/1g8NUOziTtFJIzVc2uJTcwQycC_cuTKTbErkCXW7JegM/edit?usp=sharing), especially the "Car talk head design".

If you want to talk about this more in SSB, I'd be up for that.

One side issue is that CfA is a longer and more complicated message sequence pattern. For those, I think I'd use the pattern where
> The agents in the conversation ... append and sign each message to a single circulating message that accumulates the whole conversation. In other words, there’s only one message in the conversation, it just gets longer.

**Comment by dominictarr** [comment]
@bhaugen I don't want to make this more complicated than it needs to be for this case. Like we don't need counter offers for same-as or invites. Removing those would make the Conversation-for-Action diagram much simpler, but those steps do make sense if you were selling something. `same-as` is a [performative act](https://en.wikipedia.org/wiki/Performative_utterance) so it doesn't need the fulfilment step.
At it's heart, there is just a propose and accept action. The confirm actions are optional - it's just about how consistent we want to be. For example, in some situations just proposing and accepting is enough, but in others you might want to confirm the acceptance or maybe even confirm the confirmation.

If you just have a propose then an accept, there would be a range of time where the proposal has been accepted, but the proposer hasn't noticed yet.

Sometimes you might want to over-propose, then confirm the first N things that accept the offer. So you could have an offer that becomes binding once it is confirmed, or once it is accepted. that would be 3 messages, or if the acceptor gets a confirm too that is 4.

In the case of same-as the, the important thing is how other peers react to the agreement.
because if A same-as B then followers of A also replicate B. So, the form of the agreement needs to be easy for them to verify - and that is why A has a confirm step.

**Comment by bhaugen** [comment]
>  For example, in some situations just proposing and accepting is enough, but in others you might want to confirm the acceptance or maybe even confirm the confirmation.

Would be interesting to enumerate some of the situations and their mutual-certainty requirements.

> If you just have a propose then an accept, there would be a range of time where the proposal has been accepted, but the proposer hasn't noticed yet.

Or the accepter doesn't know if the proposer has noticed it or not, or even received the acceptance. And if some subsequent action was contingent on acceptance, then the accepter can be more certain that it will happen if the proposer confirms the acceptance.

> In the case of same-as the, the important thing is how other peers react to the agreement.
because if A same-as B then followers of A also replicate B. So, the form of the agreement needs to be easy for them to verify - and that is why A has a confirm step.

Subsequent action?

**Comment by dominictarr** [comment]
@bhaugen the subsequent action is just that those peers will start to replicate the same-as feed, and private messages for A may also be encrypted to B. Also, when you open the to see A's feed, merge it with B. treat A as the "same-as" B.

**Comment by bhaugen** [comment]
>  if some subsequent action was contingent on acceptance, then the accepter can be more certain that it will happen if the proposer confirms the acceptance.

That assumes the proposer sends the confirm message *after* it takes the accepted action. Which is the correct way to do it, but still...

**Comment by dominictarr** [comment]
@bhaugen sorry if I didn't make this explicit - the all messages in an agreement contain a hash pointer to at least the previous message (and thus to all messages in the set, indirectly). to verify the confirmation, you must have the propose, accept, and confirm message - since they are cryptographically linked this can be done securely.

Although a observer may _receive_ the confirm before the accept, it's impossible for the proposer to create a valid confirm before the accept, because they'd have to know it's hash already. If you observe an invalid message, that is ignored.

**Comment by bhaugen** [comment]
@dominictarr I understood all that, but maybe was not explicit enuf myself.
> That assumes the proposer sends the confirm message after it takes the accepted action.

In this case, the accepted action is fairly trivial and probably just part of the feeds, but in some cases, it might not be. For example, I propose to send you something (which might be the start of something else). You accept. Before I confirm your acceptance, I should actually do the sending. 

But I like the pointers to previous messages, and think they are probably a requirement for message interaction patterns.

[edit] P.S. in case it's not obvious, I am thinking more generally than your particular use case. If that's annoying, I can stop and focus more narrowly.

**Comment by dominictarr** [comment]
@bhaugen I find that when thinking generally, it helps a lot to use concrete examples - so what are you sending me and why? is it a physical product? or is it data? if when illustrate the generalizations with specific examples of what it may be you sometimes realize other things that may be related or necessary in particular circumstances. If you only think abstractly some things may seem reasonable but if you can't come up with a concrete example that fits that you'll end up with YAGNIs.

To illustrate the sending something example - if it's as simple as just putting something in the mail, then it seems pretty reasonable to just have the confirmation also be the fulfillment. But if it required some significant work to be done, like, make something or wait for materials to arrive etc, then you probably want to hit the confirmation as soon as you see the accept meaning "I acknowledge and accept this obligation" then post another message when you've performed the required action.

**Comment by bhaugen** [comment]
@dominictarr all true. I was thinking of sending something electronically.

> But if it required some significant work to be done, like, make something or wait for materials to arrive etc, then you probably want to hit the confirmation as soon as you see the accept meaning "I acknowledge and accept this obligation" then post another message when you've performed the required action.

Yup. [edit] in that case, accepting the obligation might entail doing whatever you do to put it on your schedule before confirming.

**Comment by dominictarr** [comment]
@bhaugen thanks. I think I we have discussed enough to procede with this - the board pattern basically works for you and can be adapted to your goals with VF/CfA.

**Comment by bhaugen** [comment]
@dominictarr thanks for putting up with my continual broadening of your use case. Yes it works for me, and VF wants to include several interaction protocols (or at least I want it to do so...)

**Comment by dominictarr** [comment]
awesome, no it's very helpful

**Comment by bhaugen** [comment]
I think this issue is still in the todo list somewhere, at least still being discussed in SSB, so I will overrule the stalebot for now and ask @dominictarr to close the issue if I am wrong.

**Comment by dominictarr** [comment]
correct, thanks @bhaugen

**Comment by bhaugen** [comment]
I'm overruling the stalebot again, and waiting for @dominictarr to close this issue via human decision.

**Comment by bhaugen** [comment]
stalebot, STFUP...please...

**Comment by dominictarr** [comment]
@bhaugen I made a filter to just ignore stalebot messages, I only saw this because you replied ;) from your reply I get the impression stalebot posts a lot...

**Comment by bhaugen** [comment]
@dominictarr 
>  I get the impression stalebot posts a lot...

Nah, I think just quarterly. But this issue seems to be perpetually stale...so until one of us resolves it by human judgement, I intervene.
